services:
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.1
    container_name: es
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.security.enabled=false
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - elastic
  kib:
    image: docker.elastic.co/kibana/kibana:7.14.1
    container_name: kib
    environment:
      - node.name=es
      - discovery.type=single-node
      - ELASTICSEARCH_HOSTS=http://es:9200
    ports:
      - 5601:5601
    networks:
      - elastic
networks:
  elastic:
    driver: bridge
